<?php

namespace Land3;

use Psr\Log\LoggerInterface;
use Psr\Log\Test\LoggerInterfaceTest;

class ToFileTest extends LoggerInterfaceTest
{
    private string $target = '';

    private LoggerInterface $logger;

    public function setUp(): void
    {
        // TODO: Change the autogenerated stub
        $time = date("Y-m-d", time());
        $this->target = __DIR__ . '/' . $time . '.log';
        $logger = new ToFile();
        $logger->setPolicy(function () {
            return $this->target;
        });
        $this->logger = $logger;
        parent::setUp();
    }

    protected function tearDown()
    {
        // TODO: Change the autogenerated stub
        if (file_exists($this->target)) {
            unlink($this->target);
        }
        parent::tearDown();
    }

    public function getLogger()
    {
        // TODO: Implement getLogger() method.
        return $this->logger;
    }

    public function getLogs()
    {
        // TODO: Implement getLogs() method.
        $f = fopen($this->target, 'r');
        $content = stream_get_contents($f);
        $logs = explode("\n", $content);
        array_pop($logs);
        return $logs;
    }
}